import { ListDepartmentStructure } from "./DTOListDepartment";

export class ListDepartmentTree {
    StatusCode: number;
    ErrorString: null;
    ObjectReturn: ListDepartmentStructure[];
}

export const ListDepartmentTreeData = JSON.parse(JSON.stringify({
    StatusCode: 0,
    ErrorString: null,
    ObjectReturn: [
        {
            "StatusName": "Duyệt áp dụng",
            "ParentCode": null,
            "ListLocationCode": null,
            "ListLocation": [],
            "ListDepartment": [
                {
                    "StatusName": "Duyệt áp dụng",
                    "ParentCode": null,
                    "ListLocationCode": null,
                    "ListLocation": [],
                    "ListDepartment": [
                        {
                            "StatusName": "Duyệt áp dụng",
                            "ParentCode": null,
                            "ListLocationCode": null,
                            "ListLocation": [],
                            "ListDepartment": [
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 5,
                                            "PositionID": "WSMA",
                                            "Position": "Trưởng phòng Kinh doanh sỉ",
                                            "IsLeader": true,
                                            "DepartmentID": 4,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 24,
                                            "PositionID": "WSMT",
                                            "Position": "Nhân viên kinh doanh kênh MT",
                                            "IsLeader": false,
                                            "DepartmentID": 4,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 25,
                                            "PositionID": "WSGT",
                                            "Position": "Nhân viên kinh doanh kênh GT",
                                            "IsLeader": false,
                                            "DepartmentID": 4,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 26,
                                            "PositionID": "WSAD",
                                            "Position": "Admin phòng bán sỉ",
                                            "IsLeader": false,
                                            "DepartmentID": 4,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 4,
                                    "ParentID": 3,
                                    "DepartmentID": "WS",
                                    "Department": "Bán sỉ",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 6,
                                            "PositionID": "CXMA",
                                            "Position": "Trưởng phòng CX",
                                            "IsLeader": true,
                                            "DepartmentID": 5,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 27,
                                            "PositionID": "CXBS",
                                            "Position": "Giám sát hình ảnh cửa hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 5,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 28,
                                            "PositionID": "CXWA",
                                            "Position": "Web admin",
                                            "IsLeader": false,
                                            "DepartmentID": 5,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 29,
                                            "PositionID": "CXCS",
                                            "Position": "Nhân viên chăm sóc khách hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 5,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 5,
                                    "ParentID": 3,
                                    "DepartmentID": "CX",
                                    "Department": "CX",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 7,
                                            "PositionID": "ECMA",
                                            "Position": "Trưởng phòng Thương mại Điện tử",
                                            "IsLeader": true,
                                            "DepartmentID": 6,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 30,
                                            "PositionID": "ECDE",
                                            "Position": "Nhân viên phát triển TMĐT",
                                            "IsLeader": false,
                                            "DepartmentID": 6,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 31,
                                            "PositionID": "ECAD",
                                            "Position": "Admin phòng TMĐT",
                                            "IsLeader": false,
                                            "DepartmentID": 6,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 32,
                                            "PositionID": "ECCO",
                                            "Position": "Nhân viên tư vấn Online",
                                            "IsLeader": false,
                                            "DepartmentID": 6,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 33,
                                            "PositionID": "ECCL",
                                            "Position": "Trưởng nhóm tư vấn Online",
                                            "IsLeader": false,
                                            "DepartmentID": 6,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 6,
                                    "ParentID": 3,
                                    "DepartmentID": "EC",
                                    "Department": "Thương mại điện tử",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 8,
                                            "PositionID": "HIMA",
                                            "Position": "Trưởng phòng hành chánh nhân sự",
                                            "IsLeader": true,
                                            "DepartmentID": 7,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 34,
                                            "PositionID": "HIGH",
                                            "Position": "Chuyên viên Hành chính nhân sự",
                                            "IsLeader": false,
                                            "DepartmentID": 7,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 35,
                                            "PositionID": "HILD",
                                            "Position": "Chuyên viên L&D-Truyền thông nội bộ",
                                            "IsLeader": false,
                                            "DepartmentID": 7,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 36,
                                            "PositionID": "HIBP",
                                            "Position": "Chuyên viên Đối tác Nhân sự Khối vận hành",
                                            "IsLeader": false,
                                            "DepartmentID": 7,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 37,
                                            "PositionID": "HIIS",
                                            "Position": "Chuyên viên IT",
                                            "IsLeader": false,
                                            "DepartmentID": 7,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 7,
                                    "ParentID": 3,
                                    "DepartmentID": "HI",
                                    "Department": "HR-IT",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 9,
                                            "PositionID": "ACCA",
                                            "Position": "Kế toán trưởng",
                                            "IsLeader": true,
                                            "DepartmentID": 8,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 38,
                                            "PositionID": "ACGA",
                                            "Position": "Kế toán tổng hợp",
                                            "IsLeader": false,
                                            "DepartmentID": 8,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 39,
                                            "PositionID": "ACSA",
                                            "Position": "Kế toán cửa hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 8,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 40,
                                            "PositionID": "ACAD",
                                            "Position": "Admin cửa hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 8,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 8,
                                    "ParentID": 3,
                                    "DepartmentID": "AC",
                                    "Department": "Kế toán",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 54,
                                            "PositionID": "MKVM",
                                            "Position": "Phó phòng Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 55,
                                            "PositionID": "MKVL",
                                            "Position": "Trưởng nhóm Sáng tạo Hình ảnh",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 56,
                                            "PositionID": "MKTE",
                                            "Position": "Nhân viên Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 57,
                                            "PositionID": "MKVP",
                                            "Position": "Nhân viên sản xuất hình ảnh",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 58,
                                            "PositionID": "MKCP",
                                            "Position": "Nhân viên Content Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 59,
                                            "PositionID": "MKDI",
                                            "Position": "Nhân viên Digital Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 60,
                                            "PositionID": "MKVD",
                                            "Position": "Nhân viên Thiết kế",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 61,
                                            "PositionID": "MKAD",
                                            "Position": "Nhân viên Marketing Admin",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 62,
                                            "PositionID": "MKVC",
                                            "Position": "Nhân viên Visual Content Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 12,
                                            "PositionID": "MKMA",
                                            "Position": "Trưởng phòng Marketing",
                                            "IsLeader": true,
                                            "DepartmentID": 9,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 9,
                                    "ParentID": 3,
                                    "DepartmentID": "MK",
                                    "Department": "Marketing",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                },
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 13,
                                            "PositionID": "MDMA",
                                            "Position": "Trưởng phòng Merchandising",
                                            "IsLeader": true,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 63,
                                            "PositionID": "MDVM",
                                            "Position": "Phó phòng Merchandising",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 64,
                                            "PositionID": "MDID",
                                            "Position": "Nhân viên xuất nhập khẩu",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 65,
                                            "PositionID": "MDME",
                                            "Position": "Chuyên viên Merchandising",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 66,
                                            "PositionID": "MDPI",
                                            "Position": "Chuyên viên Thông tin sản phẩm",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 67,
                                            "PositionID": "MDAD",
                                            "Position": "Admin Thu mua",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 68,
                                            "PositionID": "MDAM",
                                            "Position": "Nhân viên Merchandising kiêm Admin",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 69,
                                            "PositionID": "MDOE",
                                            "Position": "Nhân viên thu mua đặt hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 70,
                                            "PositionID": "MDBL",
                                            "Position": "Trưởng nhóm Phát triển thương hiệu",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 71,
                                            "PositionID": "MDBD",
                                            "Position": "Nhân viên Digital Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 72,
                                            "PositionID": "MDBC",
                                            "Position": "Nhân viên content Marketing",
                                            "IsLeader": false,
                                            "DepartmentID": 10,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 10,
                                    "ParentID": 3,
                                    "DepartmentID": "MD",
                                    "Department": "Merchandising",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                }
                            ],
                            "ListPosition": [],
                            "Code": 3,
                            "ParentID": 2,
                            "DepartmentID": "HO",
                            "Department": "Khối văn phòng",
                            "Brieft": null,
                            "Phone": null,
                            "Fax": null,
                            "Remark": null,
                            "Config": null,
                            "TypeData": 1,
                            "OrderBy": null,
                            "StatusID": 2
                        },
                        {
                            "StatusName": "Duyệt áp dụng",
                            "ParentCode": null,
                            "ListLocationCode": null,
                            "ListLocation": [],
                            "ListDepartment": [
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 2,
                                            "PositionID": "OPMA",
                                            "Position": "Trưởng phòng Vận hành bán lẻ",
                                            "IsLeader": true,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 3,
                                            "PositionID": "OPSM",
                                            "Position": "Cửa hàng trưởng",
                                            "IsLeader": true,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 14,
                                            "PositionID": "OPSF",
                                            "Position": "Giám sát cửa hàng- ngành thực phẩm",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 15,
                                            "PositionID": "OPSH",
                                            "Position": "Giám sát cửa hàng- ngành gia dụng",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 16,
                                            "PositionID": "OPSW",
                                            "Position": "Giám sát cửa hàng- ngành wellness",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 17,
                                            "PositionID": "OPCF",
                                            "Position": "Nhân viên tư vấn thực phẩm",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 18,
                                            "PositionID": "OPCH",
                                            "Position": "Nhân viên tư vấn gia dụng",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 19,
                                            "PositionID": "OPCW",
                                            "Position": "Nhân viên tư vấn wellness",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 20,
                                            "PositionID": "OPAF",
                                            "Position": "Nhân viên bán hàng thực phẩm",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 21,
                                            "PositionID": "OPAH",
                                            "Position": "Nhân viên bán hàng gia dụng",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 22,
                                            "PositionID": "OPCC",
                                            "Position": "Thu ngân",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 23,
                                            "PositionID": "OPSD",
                                            "Position": "Nhân viên giao hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 12,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 12,
                                    "ParentID": 11,
                                    "DepartmentID": "OP",
                                    "Department": "Vận hành bán lẻ",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                }
                            ],
                            "ListPosition": [],
                            "Code": 11,
                            "ParentID": 2,
                            "DepartmentID": "POS",
                            "Department": "Khối cửa hàng",
                            "Brieft": null,
                            "Phone": null,
                            "Fax": null,
                            "Remark": null,
                            "Config": null,
                            "TypeData": 1,
                            "OrderBy": null,
                            "StatusID": 2
                        },
                        {
                            "StatusName": "Duyệt áp dụng",
                            "ParentCode": null,
                            "ListLocationCode": null,
                            "ListLocation": [],
                            "ListDepartment": [
                                {
                                    "StatusName": "Duyệt áp dụng",
                                    "ParentCode": null,
                                    "ListLocationCode": null,
                                    "ListLocation": [],
                                    "ListDepartment": null,
                                    "ListPosition": [
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 11,
                                            "PositionID": "LGMA",
                                            "Position": "Trưởng phòng Logistics",
                                            "IsLeader": true,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 41,
                                            "PositionID": "LGDM",
                                            "Position": "Phó phòng Logistics",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 42,
                                            "PositionID": "LGDL",
                                            "Position": "Thủ kho",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 43,
                                            "PositionID": "LGDD",
                                            "Position": "Phó thủ kho",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 44,
                                            "PositionID": "LGFL",
                                            "Position": "Phó thủ kho - nhóm thực phẩm",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 45,
                                            "PositionID": "LGOL",
                                            "Position": "Thủ kho Online",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 46,
                                            "PositionID": "LGOA",
                                            "Position": "Admin kho Online",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 47,
                                            "PositionID": "LGOP",
                                            "Position": "Nhân viên soạn hàng Online",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 48,
                                            "PositionID": "LGOS",
                                            "Position": "Nhân viên quét đối soát Online",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 49,
                                            "PositionID": "LGOW",
                                            "Position": "Nhân viên đóng và giao hàng",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 50,
                                            "PositionID": "LGOC",
                                            "Position": "Nhân viên xử lý đơn hàng sàn TMĐT",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 51,
                                            "PositionID": "LGRC",
                                            "Position": "Nhân viên điều phối bán lẻ",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 52,
                                            "PositionID": "LGWC",
                                            "Position": "Nhân viên điều phối bán sỉ",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        },
                                        {
                                            "DepartmentCode": null,
                                            "ReportToCode": null,
                                            "GroupPositionCode": null,
                                            "StatusName": null,
                                            "ListChild": null,
                                            "Code": 53,
                                            "PositionID": "LGWE",
                                            "Position": "Nhân viên kho",
                                            "IsLeader": false,
                                            "DepartmentID": 14,
                                            "ReportTo": null,
                                            "GroupPosition": null,
                                            "Remark": null,
                                            "OrderBy": null,
                                            "ListOfRoles": null,
                                            "Config": null,
                                            "StatusID": 0
                                        }
                                    ],
                                    "Code": 14,
                                    "ParentID": 13,
                                    "DepartmentID": "LG",
                                    "Department": "Logistics",
                                    "Brieft": null,
                                    "Phone": null,
                                    "Fax": null,
                                    "Remark": null,
                                    "Config": null,
                                    "TypeData": 1,
                                    "OrderBy": null,
                                    "StatusID": 2
                                }
                            ],
                            "ListPosition": [],
                            "Code": 13,
                            "ParentID": 2,
                            "DepartmentID": "SP",
                            "Department": "Kho vận",
                            "Brieft": null,
                            "Phone": null,
                            "Fax": null,
                            "Remark": null,
                            "Config": null,
                            "TypeData": 1,
                            "OrderBy": null,
                            "StatusID": 2
                        }
                    ],
                    "ListPosition": [
                        {
                            "DepartmentCode": null,
                            "ReportToCode": null,
                            "GroupPositionCode": null,
                            "StatusName": null,
                            "ListChild": null,
                            "Code": 4,
                            "PositionID": "BDVS",
                            "Position": "Phó giám đốc phụ trách Kinh doanh",
                            "IsLeader": false,
                            "DepartmentID": 2,
                            "ReportTo": null,
                            "GroupPosition": null,
                            "Remark": null,
                            "OrderBy": null,
                            "ListOfRoles": null,
                            "Config": null,
                            "StatusID": 0
                        },
                        {
                            "DepartmentCode": null,
                            "ReportToCode": null,
                            "GroupPositionCode": null,
                            "StatusName": null,
                            "ListChild": null,
                            "Code": 1,
                            "PositionID": "BDGD",
                            "Position": "Giám đốc",
                            "IsLeader": true,
                            "DepartmentID": 2,
                            "ReportTo": null,
                            "GroupPosition": null,
                            "Remark": null,
                            "OrderBy": null,
                            "ListOfRoles": null,
                            "Config": null,
                            "StatusID": 0
                        },
                        {
                            "DepartmentCode": null,
                            "ReportToCode": null,
                            "GroupPositionCode": null,
                            "StatusName": null,
                            "ListChild": null,
                            "Code": 10,
                            "PositionID": "BDVM",
                            "Position": "Phó giám đốc phụ trách MD và Supply Chain",
                            "IsLeader": false,
                            "DepartmentID": 2,
                            "ReportTo": null,
                            "GroupPosition": null,
                            "Remark": null,
                            "OrderBy": null,
                            "ListOfRoles": null,
                            "Config": null,
                            "StatusID": 0
                        }
                    ],
                    "Code": 2,
                    "ParentID": 1,
                    "DepartmentID": "BD",
                    "Department": "Ban giám đốc",
                    "Brieft": null,
                    "Phone": null,
                    "Fax": null,
                    "Remark": null,
                    "Config": null,
                    "TypeData": 1,
                    "OrderBy": null,
                    "StatusID": 2
                }
            ],
            "ListPosition": [],
            "Code": 1,
            "ParentID": null,
            "DepartmentID": "BOM",
            "Department": "Hội đồng thành viên",
            "Brieft": null,
            "Phone": null,
            "Fax": null,
            "Remark": null,
            "Config": null,
            "TypeData": 1,
            "OrderBy": null,
            "StatusID": 2
        },
    ],
})) 